### ISSUE TITLE
Z work position in tool change

### ISSUE THREAD

**Issue by Sualc** [duembeg/gsat#7]
Hello  Duembeg,

Your software steal to be the strongest I tried.
One suggestion this time: 
I found will be very useful a button to define the new Z work position after a tool change.
The command in Gcode is G10 L2 P1 Z(actual Z machine position).

After "touch" the piece with the new tool, this new button will get the actual Z machine position to do the G10 command.

Better will be if after the G10 command the Z axis go up to the clearance plane.
Or some coordinate predefined as "clearance plane".
This will confirm the new Z work position with the machine move and avoid to crash with some other part of the piece.

I am not sure if I explain it well for you, bur I think you will understand.

Other thing: What about the XY graphic to visualize the next moves?
Again I tell you I prefer one 2D plane for XY and only a Z level will be nice.
One 2D plane can show exacts distances easy than a 3D one.
Most part of time I make 2D1/2 works.
3D works are not so often.

Witch CAM are you using?     

PS: I edited a little your code to change the HOME function.
I only changed the command value:
gGRBL_CMD_EXE_HOME_CYCLE      = "$H\n"

value before my change = "G28 X0 Y0 Z0\n"
In "config.py" file.

I am thinking in make the same for the command:
gGRBL_CMD_RESET_TO_ZERO_POS   = "G92 X0 Y0 Z0\n"

But I don't know If I need to read with "?" the machine's Z position to send later the 
G10 L2 P1 Z(Z machine position)
Or G10 L2 P1 Z<"ZVAL"> will make the trick.
"Z<"ZVAL"> or Z<"VAL">?"
Anyway I prefer listen the father of this nice program.

**Comment by duembeg** [comment]
Hi for a while now the jog panel has the ability to add custom buttons with, you can add your own snippets of code to send to the machine when clicked.
